### ISSUE TITLE
Kipoi error

### ISSUE THREAD

**Issue by evanseitz** [bernardo-de-almeida/DeepSTARR#2]
Hi, I'm receiving the following Kipoi error:

`ValueError: Error when checking input: expected input_12 to have 3 dimensions, but got array with shape (4, 249, 4, 1)`

when using any of the following:

(1) 
```
pred = model.pipeline.predict_example(batch_size=4)`
```
(2) 
```
# Download example dataloader kwargs
dl_kwargs = model.default_dataloader.download_example('example')
# Get the dataloader and instantiate it
dl = model.default_dataloader(**dl_kwargs)
# get a batch iterator
batch_iterator = dl.batch_iter(batch_size=4)
for batch in batch_iterator:
# predict for a batch
batch_pred = model.predict_on_batch(batch['inputs'])
```
(3) 
```
dl_kwargs = {'intervals_file': intervals_file_motif, 'fasta_file': fasta_file_motif}
dl = model.default_dataloader(**dl_kwargs)
batch_iterator = dl.batch_iter(batch_size=4)
pred = model.pipeline.predict(dl_kwargs, batch_size=4)
```

(1) and (2) are from http://kipoi.org/models/DeepSTARR/, while (3) uses a custom intervals and fasta file, which I can confirm has worked for other kipoi models (e.g., BPNet).

My environment is the same as in your README.md, with the addition of `pip install kipoi` and `pip install kipoiseq` -- any help would be greatly appreciated.

**Comment by bernardo-de-almeida** [comment]
Hi @evanseitz , can you try building the environment with the code below, as suggested by kipoi [here](http://kipoi.org/models/DeepSTARR/)? Then the commands you tested should work.
There was a [problem](https://github.com/kipoi/models/pull/327) before when building the DeepSTARR environment from kipoi but we solved it now.

```
kipoi env create DeepSTARR
source activate kipoi-DeepSTARR
```
Then in python:
```
import kipoi
model = kipoi.get_model('DeepSTARR')
```
