### ISSUE TITLE
how to make figure 1A

### ISSUE THREAD

**Issue by BenxiaHu** [bernardo-de-almeida/DeepSTARR#4]
Hello,
    The DeepSTARR looks a great tool to predict enhancer activity from DNA sequences.
    Would you like to tell me whether DeepSTARR can predict the motif from gene promoters? I also want to plot the figure 1A.

<img width="1252" alt="image" src="https://github.com/bernardo-de-almeida/DeepSTARR/assets/12387462/53ba9660-f939-426c-b6ba-86662af50f6c">

**Comment by bernardo-de-almeida** [comment]
Hi,
The DeepSTARR model was trained on enhancer sequences so it is not a good model to evaluate promoter sequences. What you want would be possible if you train a DeepSTARR-like model on promoter activity data (or maybe DNA accessibility data that is more common and should work well) and then use that new model to evaluate promoters in a similar way as I do here.
Hope it helps!
